### Part-I: Write a method for sigmoid function

1. Write a function, mysigmoid(x), that takes the real number x and returns the sigmoid value using math.exp().
2. Call mysigmoid() with x=4 and print the sigmoid value of 4.
3. Now, find the sigmoid values for x=[1, 2, 3]. Observe the results.
4. Rewrite mysigmoid() using np.exp() function.
5. Now call your function with x=[1, 2, 3] and observe the results
6. Understand the difference between scalar and vector. 

In [1]:
import numpy as np
import math

In [2]:
def mysigmoid(x):
    print(math.exp(x))

In [3]:
mysigmoid(4)

54.598150033144236


In [4]:
x = [1,2,3]
for i in x:
    mysigmoid(i)

2.718281828459045
7.38905609893065
20.085536923187668


In [5]:
def mysigmoid(x):
    print(np.exp(x))

In [6]:
x = [1,2,3]
for i in x:
    mysigmoid(i)

2.718281828459045
7.38905609893065
20.085536923187668


### Part-II: Gradient or derivative of sigmoid function
We compute gradients to optimize loss functions using backpropagation.
s_derivative = s * (1 – s), where s = sigmoid(X)
Write a function, sig_derivative(s) that returns the gradient of s. You
should call your earlier function, mysigmoid() to compute the sigmoid
value.

In [7]:
def sig_derivative(s):
    return s*(1.0-s)

In [8]:
mysigmoid(sig_derivative(4))

6.14421235332821e-06


### Part-III: Write a method image_to_vector()
    X.shape is used to get the shape (dimension) of a matrix/vector X.
    X.reshape(...) is used to reshape X into some other dimension.
Image Representation: an image is represented by a 3D array of shape
(length,height,depth=3). However, when you read an image as the input of
an algorithm you convert it to a vector of shape (length∗height∗3,1) . In
other words, you "unroll", or reshape, the 3D array into a 1D vector.

####    1.Now, implement image_to_vector() that takes an input of shape(length, height, 3) and returns a vector of shape (length*height*3, 1).For example, if you would like to reshape an array v of shape (a, b, c)into a vector of shape (a*b,c) you would do:
v = v.reshape((v.shape[0]*v.shape[1], v.shape[2]))

#v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c

In [9]:
def image_to_vector():
    length, height, depth = int(input('image length: ')),int(input('image height: ')), int(input('image depth: '))
    return (length*height*depth, 1)

#### 2). Test with a 3x3x2 array of values of RGB color values.

In [10]:
image_to_vector()

image length: 3
image height: 3
image depth: 2


(18, 1)

### Part-IV: Write a method normalizeRows() Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1). You can use np.linalg.norm() method.

In [13]:
def normalizeRows(x):
    x_norm = np.linalg.norm(x)
    x = x / x_norm
    return x

In [19]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

In [20]:
normalizeRows(x)

array([[0.        , 0.33968311, 0.45291081],
       [0.1132277 , 0.67936622, 0.45291081]])

### Part-V: Multiplication and Vectorization Operations
In deep learning, you deal with very large datasets. So multiplication takeslong execution time than vectorization.

    1). For the following two vectors, find the multiplication value and the dot product. First compute multiplication and dot product manually. Then, you can use np.multiply() and np.dot() functions.

a).
x1 = [9, 2, 5]
x2 = [7, 2, 2]

In [21]:
x1 = [9, 2, 5]
x2 = [7, 2, 2]

np.multiply(x1,x2)

array([63,  4, 10])

In [22]:
np.dot(x1,x2)

77

b).
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7]
x2 = [7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3]

In [23]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7]
x2 = [7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3]

np.multiply(x1,x2)

array([63,  4, 10,  0,  0, 63, 10,  0,  0,  0, 81,  4, 25,  0,  0, 32, 25,
       21])

In [24]:
np.dot(x1,x2)

338

2). Create two random vectors of N elements, perform multiplication and
vectorization operations and print the respective running times. Is running
time of vectorization is less?.

In [33]:
import time

In [34]:
x1 = [8, 5, 5]
x2 = [4, 1, 2]

tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 47
 ----- Computation time = 0.0ms
outer = [[32  8 16]
 [20  5 10]
 [20  5 10]]
 ----- Computation time = 0.0ms


### Part-VI: Implement L1 and L2 loss functions
The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions (ypred) are from the true values (y). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.

    1). Write a method loss_l1(y, ypred) that takes the actual value y and predicted value ypred and returns l1 loss value. Test your function with the following vectors.
    y = np.array([1, 0, 0, 1, 1])
    ypred = np.array([.9, 0.2, 0.1, .4, .9])
    // Your output will be 1.1

In [25]:
def loss_L1(y, ypred):
    loss = np.sum(abs(y - ypred))
    return loss

In [26]:
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([.9, 0.2, 0.1, .4, .9])

loss_L1(y, ypred)

1.1

 2). Write a method loss_l2(y, ypred) that takes the actual value y and
predicted value ypred and returns l2 loss value. Test your function with
the following vectors.
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([.9, 0.2, 0.1, .4, .9])
// Your output will be 0.43

In [28]:
def  loss_l2(y, ypred):
    loss = np.dot(y - ypred, y - ypred)
    return loss

In [29]:
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([.9, 0.2, 0.1, .4, .9])

loss_l2(y, ypred)

0.43